key-add bug fixed

diff --git a/git-shell-commands/key-add b/git-shell-commands/key-add
--- a/git-shell-commands/key-add
+++ b/git-shell-commands/key-add
@@ -5,13 +5,11 @@ keyfile=$(mktemp)
 echo "$key" > $keyfile
 
 # Generate a fingerprint
-fingerprint=$(ssh-keygen -lf $keyfile)
-
-# Check for errors
-[ $(echo "$fingerprint" | egrep -c '(R|D)SA') -eq 0 ] {
-	echo "Error: Invalid Fingerprint"
-	rm $keyfile
-	exit 1
+fingerprint=`ssh-keygen -lf $keyfile` 
+[ "$?" != "0" ] && {
+  echo "Error: Not a Keyfile"
+  rm $keyfile
+  exit 1
 }
 
 cat $keyfile >> $HOME/.ssh/authorized_keys
