Mainly dzen changes and gitshell

diff --git a/git-shell-commands/log b/git-shell-commands/log
--- a/git-shell-commands/log
+++ b/git-shell-commands/log
@@ -1,10 +1,19 @@
 #!/bin/bash
 # Print Repo Log
 [ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
-    echo "Usage: $(basename $0) <dir name>"
+    echo "Usage: $(basename $0) <repo> <branch>"
     exit 1
 }
 
 cd "$1"
-git log --pretty='format:%Cgreen%cn %Cred%ai %Creset- %s'
+branch="$2"
+
+[[ -z $branch ]] && branch='master'
+
+! git branch | grep "$branch\$" &>/dev/null && {
+    echo "Branch '$branch' not found"
+    exit 1
+}
+
+git log "$branch" --pretty=format:'%Cgreen%h | %Cblue%an | %Creset- %s' -30 | column -t -s '|' 2>/dev/null
 exit 0
diff --git a/git-shell-commands/rm b/git-shell-commands/rm
--- a/git-shell-commands/rm
+++ b/git-shell-commands/rm
@@ -1,43 +1,25 @@
 #!/bin/bash
 # Removes Repo
-
-error(){
-    echo "$1"
-    exit 1
-}
-
 [ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
-    echo "Usage: $(basename $0) <dir name>"
+    echo "Usage: $(basename $0) <repo>"
     exit 1
 }
 
-echo -ne "Delete '"$1"' [y/n]?: "
-read ans
+[[ ! -d $1 ]] && {
+    echo "Repo '$1' does not exist."
+    exit 1
+}
 
+echo -ne "Delete '$1' [y/n]?: "
+read ans
 
 # Attempts to prevent going outside pwd
 case "$ans" in
-    Yes|yes|YES|y)
-        ls -A | grep "$1" > /dev/null
-        [ "$?" != "0" ] && error "Dir '$1' does not exist."
-        [ ! -d "$1" ] && error "'$1' is not a directory"
-
-        # only ask for backup if they want to remove 
-        # repo
-        echo -ne "Backup '"$1"' [y/n]?: "
-        read bkans
-        case "$bkans" in
-            Yes|yes|YES|y)
-                $HOME/git-shell-commands/tar "$1" || {
-                        error "Backup error."
-                        exit 1
-                    }
-                ;;
-            *)
-                echo "Backup aborted."
-                ;;
-        esac
-
+    Yes|yes|y)
+        "$HOME"/git-shell-commands/tar "$1" || {
+            echo "Backup error."
+            exit 1
+        }
 
         rm -rf "$1" || error "Remove error."
         echo "Remove succeeded."
diff --git a/task b/task
--- a/task
+++ b/task
@@ -1,4 +1,29 @@
 #!/bin/bash
+logFile=$2
+
 source $(dirname $(readlink -m $0))/task_source
-[[ $# -lt 2 ]] && exit 1
-_task "$@"
+
+[[ $# -lt 2 ]] && {
+cat << EOF
+task - Run command(s) with output to file/stream with progress indicator
+Usage: task <commands string> [logfile]
+EOF
+exit 1
+}
+
+commands=$1
+
+function message()
+{
+    local s=${commands:0:25}
+    if (( ${#commands} >= 25 )); then
+        s="$s..."
+    fi
+    printf "%s" "$s"
+}
+
+if [[ "$commands" =~ "sudo" ]]; then
+    sudo -v || exit 1
+fi
+
+eval "$commands" &>>$logFile & waitProgress "$(message)" || echo "Command failed"
diff --git a/task_source b/task_source
--- a/task_source
+++ b/task_source
@@ -1,46 +1,41 @@
+# vim: set ft=sh
 export logFile=${logFile:-/dev/null}
 
-_FAIL="[-]"
-_SUCCESS="[+]"
-_NOTE="[*]"
- 
-function _progress()
+function waitProgress()
 {
-    local PID=$1
-    local msg="$2"
+    local pid=$!
+    local msg=$1
     local delay=0.25
     local str=("/" "-" "\\" "|")
     local index=0
- 
-    while kill -0 $PID &>/dev/null; do
-        echo -ne "\r[${str[$index]}] "$msg"  "
-        sleep $delay
-        index=$(bc <<< "(($index+1) % ${#str[@]})")
-    done
-}
- 
- 
-function _task()
-{
-    eval "$1" &>> "${logFile}" &
-    local pid=$!
- 
-    if [ -t 1 ]; then
-        _progress $pid "$2"
+    local _FAIL="[-]"
+    local _SUCCESS="[+]"
+    local _NOTE="[*]"
+    
+    [[ -z $msg ]] && { 
+        msg="Waiting..."
+    }
+
+    if [[ -t 1 ]]; then
+        # produces spinner indicator
+        while kill -0 $pid &>/dev/null; do
+            echo -ne "\r[${str[$index]}] $msg  "
+            sleep $delay
+            index=$(( $(( $index + 1 )) % ${#str[@]} ))
+        done
     else
-        echo -en "\r[...] "$2""
-        wait $pid
+        # or a simpler indicator
+        echo -en "\r[...] $msg"
     fi
- 
-    wait $pid
- 
-    local ret=$?
-    if ! (( $ret )); then
-        echo -en "\r$_SUCCESS "$2"  \n"
-    else 
-        echo -en "\r$_FAIL "$2"  \n" 
+
+    # block
+    if wait $pid ; then
+        ret=$?
+        echo -en "\r$_SUCCESS $msg    \n"
+    else
+        ret=$?
+        echo -en "\r$_FAIL $msg       \n"
     fi
- 
+
     return $ret
 }
- 
