Fixed bug

diff --git a/git-shell-commands/rm b/git-shell-commands/rm
--- a/git-shell-commands/rm
+++ b/git-shell-commands/rm
@@ -1,5 +1,6 @@
 #!/bin/bash
 # Removes Repo
+
 error(){
   echo "$1"
   exit 1
@@ -19,10 +20,17 @@ case "$ans" in
     ls | grep "$1" > /dev/null
     [ "$?" != "0" ] && error "Dir '$1' does not exist."
     [ ! -d "$1" ] && error "Dir '$1' does not exist."
-    ./tar "$1" || error "Backup"
+
+    $HOME/git-shell-commands/tar "$1" || {
+      error "Backup Error."
+      exit 1
+    }
+
     rm -r "$1" || error "Error."
     echo "Success."
+    
     ;;
+
   *)
     echo "Aborted."
     exit 1
diff --git a/git-shell-commands/tar b/git-shell-commands/tar
--- a/git-shell-commands/tar
+++ b/git-shell-commands/tar
@@ -10,15 +10,18 @@
   exit 1
 }
 
-d=$(date +%F_%H_%M_%S)
-arg_fixed=$(echo $1 | sed 's/ /_/g')
-
-outdir=$HOME/backups ; mkdir -p $outdir
-out=$outdir/${arg_fixed}_$d.tar 
-
-tar -cf $out "$1" || {
-  echo "Backup failed"
-  exit 1
+_tar () {
+  d=$(date +%F_%H_%M_%S)
+  arg_fixed=$(echo $1 | sed 's/ /_/g')
+  
+  outdir=$HOME/backups ; mkdir -p $outdir
+  out=$outdir/${arg_fixed}_$d.tar 
+  
+  tar -cf $out "$1" || {
+    echo "Backup failed"
+    exit 1
+  }
+  echo "Backup Succeeded '$(basename $out)'"
 }
 
-echo "Backup Succeeded '$(basename $out)'"
+_tar "$1"
